theme: jekyll-theme-minimal
title: Nichitha
description: first-year Computer Science student at CBIT, Hyderabad. I'm at the beginning of my journey — building my foundations in problem solving, learning data structures. I don't have big projects yet. I'm here to grow, experiment.
